// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: [
        "src/index.ts",
        "src/tsup.config.ts",
        "src/unbuild.config.ts",
        "src/presets/index.ts",
        "src/cli/index.ts",
    ],
    project: ["src/**/*.ts"],
    ignoreBinaries: ["knip", "tsx"],
    ignoreDependencies: [
        "@rad/config",
        // CLI dependencies - used in src/cli but knip can't trace unbuild entries
        "@clack/prompts",
        "cac",
        "consola",
        "defu",
        "execa",
        "picocolors",
        "zod",
    ],
    ignore: [
        // CLI and presets are built via unbuild entries, knip can't trace them
        "src/cli/**",
        "src/presets/**",
    ],
});
