// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: [
        "src/index.ts",
        "src/tsup.config.ts",
        "src/unbuild.config.ts",
        "src/presets/index.ts",
        "src/cli/index.ts",
    ],
    project: ["src/**/*.ts"],
    // WHY: knip/tsx not in devDeps, used in scripts
    ignoreBinaries: ["knip", "tsx"],
    ignoreDependencies: [
        // WHY: workspace config dep, not directly imported
        "@rad/config",
        // WHY: CLI deps used in src/cli — knip can't trace unbuild entries
        "@clack/prompts",
        "cac",
        "consola",
        "defu",
        "execa",
        "picocolors",
        "zod",
    ],
    // WHY: CLI and presets built via unbuild entries, knip can't trace them
    ignore: [
        "src/cli/**",
        "src/presets/**",
    ],
});
